### ISSUE TITLE
不能加载libopencv_java.so

### ISSUE THREAD

**Issue by jingzhanwu** [gcoulby/OpenCVDistanceCamera#3]
运行程序时，出现错误
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/org.opencv.engine-1/lib/arm/libopencv_java.so" is 32-bit instead of 64-bit
org.opencv.android.AsyncServiceHelper.loadLibrary(AsyncServiceHelper.java:347)
12-11 18:31:54.780 24291-24291/uk.co.apalis.myapplication W/System.err:     at org.opencv.android.AsyncServiceHelper.initOpenCVLibs(AsyncServiceHelper.java:373)
12-11 18:31:54.780 24291-24291/uk.co.apalis.myapplication W/System.err:     at org.opencv.android.AsyncServiceHelper.access$000(AsyncServiceHelper.java:18)
12-11 18:31:54.780 24291-24291/uk.co.apalis.myapplication W/System.err:     at org.opencv.android.AsyncServiceHelper$3.onServiceConnected(AsyncServiceHelper.java:300)

我的opencv已经安装到手机上了，我使用的是android6.0和7.0系统。
我的gradle配置如下
compileSdkVersion 26
    //buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "uk.co.apalis.myapplication"
        minSdkVersion 15
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
请问这是什么问题，怎么解决？

**Comment by sdsouza33** [comment]
When will this get fixed?
